### PR TITLE
Create TreeSort.java

### PR DESCRIPTION
**Pull request by Shivani-001**
Tree Sort in Java is added here!

### CODE REVIEW

**Comment by Shivani-001** [comment]
Kindly Merge this request asap :))

**Review by Abishethvarman — CHANGES_REQUESTED** [review]
we need the readme file. not the c implementation.

**Review by Abishethvarman — APPROVED** [review]
As the last day of hacktoberfest, Im approving this PR. But follow the code of conduct

**Comment by Abishethvarman** [comment]
@Thevapriyan07 approve it in a fast manner

**Review by Thevapriyan07 — APPROVED** [review]

**Pull request merged**
