### PR TITLE
PR Algo-quick sort in java 

### PR DESCRIPTION
**Pull request by CheetahCodes21**
updated to md

### CODE REVIEW

**Review by Thevapriyan07 — APPROVED** [review]
good

**Comment by CheetahCodes21** [comment]
> good

Appreciate your response :)

**Comment by Abishethvarman** [comment]
Rename the title of the PR like "PR: Algo algorithm-name in programming-language "  @CheetahCodes21

**Review by Abishethvarman — CHANGES_REQUESTED** [review]
Rename the title of the PR according to my comment

**Review by Thevapriyan07 — APPROVED** [review]

**Comment by Thevapriyan07** [comment]
star this repo @CheetahCodes21

**Review by Abishethvarman — APPROVED** [review]

**Review by Abishethvarman — CHANGES_REQUESTED** [review]
"1-data-structures/1-java/quick-sort" this path should be "2-algorithm/1-java/quick-sort.MD"

**Comment by Abishethvarman** [comment]
You better close this PR and create a new PR in correct file location

**Comment by Abishethvarman** [comment]
https://github.com/Abishethvarman/programming-resources/issues/58 already the issue has addressed. So better try in our issues

**Pull request closed without merging**
