### PR TITLE
PR: Algo Linear search in C

### PR DESCRIPTION
**Pull request by sowmyasri-Z**
This PR is about Linear search in C

### CODE REVIEW

**Comment by sowmyasri-Z** [comment]
can u please check my work...

**Review by Abishethvarman — CHANGES_REQUESTED** [review]
https://github.com/Abishethvarman/programming-resources/blob/main/2-algorithms/1-java/2-quick-sort.MD refer this and create a readme file for linear search in C programming

**Comment by Abishethvarman** [comment]
> can u please check my work...

check the reference PR and do the same for this too

**Comment by sowmyasri-Z** [comment]
okay!

**Comment by sowmyasri-Z** [comment]
created reame file. can u please check..

**Review by Abishethvarman — APPROVED** [review]
Approved to merge

**Comment by Abishethvarman** [comment]
@Thevapriyan07 please review and merge

**Review by Thevapriyan07 — APPROVED** [review]
Approve to merge

**Pull request merged**
