### PR TITLE
 PR: Algo  selection-sort in Java

### PR DESCRIPTION
**Pull request by Sanchayan12**
This is PR for selection sort in java

### CODE REVIEW

**Review by Thevapriyan07 — CHANGES_REQUESTED** [review]
change  the file name

**Comment by Sanchayan12** [comment]
I have already change name

**Comment by Sanchayan12** [comment]
I have made the changes

**Comment by Abishethvarman** [comment]
Mistake from myside. I edited my comment. Change accordingly
Rename the title of the PR like "PR: Algo <<algorithm name in <<programming language "

**Review by Thevapriyan07 — APPROVED** [review]

**Comment by Abishethvarman** [comment]
closed due to file relocation issue

**Pull request closed without merging**
