### PR TITLE
PR Algo Linear Search in Python 

### PR DESCRIPTION
**Pull request by shrey141102**
closes issue #81 
please add `hacktoberfest-accepted` labels

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Seems good

**Comment by Abishethvarman** [comment]
> closes issue #81 please add `hacktoberfest-accepted` labels


Add the proper description

**Comment by Abishethvarman** [comment]
@shrey141102  dont forget to star this Repo

**Review by Thevapriyan07 — APPROVED** [review]
Star this repo

**Pull request merged**
