### PR TITLE
PR: Algo selection-sort in C programming

### LINKED ISSUE #48: Algo Selection Sort in C programming

### PR DESCRIPTION
**Pull request by suraakhila1**

### CODE REVIEW

**Comment by Abishethvarman** [comment]
> _ No description provided. _

Add proper description

**Review by Abishethvarman — CHANGES_REQUESTED** [review]
image
 replace it by renaming in a correct order. 2-algorithms/c-program/selection-sort.MD

**Review by Abishethvarman — COMMENTED** [review]
Content is ok, only consider the right path and the file name

**Comment by Abishethvarman** [comment]
Make sure to star this repository @suraakhila1

**Comment by suraakhila1** [comment]
Sure sir.

**Comment by suraakhila1** [comment]
sir could please review the issue if you want any modifications update sir.

**Review by Abishethvarman — COMMENTED** [review]
Seems good

**Comment by Abishethvarman** [comment]
> sir could please review the issue if you want any modifications update sir.

Add the proper description to the PR

**Comment by Abishethvarman** [comment]
> image replace it by renaming in a correct order. 2-algorithms/c-program/selection-sort.MD

I have placed your file in the correct path. Please have a look and do the same for future contribution.

**Review by Thevapriyan07 — APPROVED** [review]
Approve to merge

**Pull request closed without merging**
