### PR TITLE
LinkedList DS in python issue completed

### PR DESCRIPTION
**Pull request by gautam-bhagat**
Hey,
The issue #26 has been solved!!
You can merge it with the base repository!

Regards,
Gautam Bhagat.

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Seems good

**Comment by Abishethvarman** [comment]
@Thevapriyan07 please review this and merge with correct labels.

**Comment by gautam-bhagat** [comment]
> Seems good

Thanks!!

**Review by Thevapriyan07 — APPROVED** [review]
good

**Pull request merged**
