### PR TITLE
PR: Algo in insertion-sort in Java

### PR DESCRIPTION
**Pull request by Sanchayan12**
This is a PR for insertion sort

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Approved to merge

**Review by Thevapriyan07 — CHANGES_REQUESTED** [review]
you have to change the file name as 5-insertion-sort.MD

**Comment by Sanchayan12** [comment]
I have made the change

**Comment by Abishethvarman** [comment]
> I have made the change

file name not the title

**Comment by Abishethvarman** [comment]
> This is a PR for insertion sort

what language?

**Comment by Abishethvarman** [comment]
Rename the title of the PR like "PR: Algo <algorithm name> in <programming language >"
Rename the filename by adding .MD in the extention.

**Comment by Sanchayan12** [comment]
I have made the changes

**Comment by Abishethvarman** [comment]
Mistake from myside. I edited my comment. Change accordingly

**Comment by Abishethvarman** [comment]
Mistake from myside. I edited my comment. Change accordingly
Rename the title of the PR like "PR: Algo <<algorithm name in <<programming language "

**Review by Thevapriyan07 — APPROVED** [review]

**Pull request merged**
