### PR TITLE
PR: Algo Selection Sort in JavaScript

### PR DESCRIPTION
**Pull request by pranav-kale-01**
I've added the Selection Sort algorithm using JavaScript. Along with the explanation I have also added the Time and Space complexity of the algorithm.

Fixes (#50)

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Well articulated

**Comment by RaamVijith** [comment]
Seems good

**Comment by Abishethvarman** [comment]
@Thevapriyan07 this PR is still pending. Make approve and merge it

**Review by Thevapriyan07 — APPROVED** [review]
Approve to merge

**Pull request merged**
