### PR TITLE
PR: Algo quick-sort in Java

### PR DESCRIPTION
**Pull request by CheetahCodes21**
This is a Java code demonstrating Quick Sort Algorithm.

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Approved to Merge @Thevapriyan07

**Review by Thevapriyan07 — APPROVED** [review]
good

**Comment by Thevapriyan07** [comment]
star this repo @CheetahCodes21

**Comment by CheetahCodes21** [comment]
@Thevapriyan07 please can I help you guys with the Code Review. It would be of great help to me as well...

**Comment by Abishethvarman** [comment]
> @Thevapriyan07 and @Abishethvarman, please can I help you guys with the Code Review. It would be of great help to me as well...

Go ahead, review the PRs if not addressed

**Pull request merged**
